[project]
name = "dotfiles"
version = "0.1.0"
description = "Dotfiles for personal configuration"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pre-commit>=4.3.0",
    "yamllint>=1.35.1",
]
